# Generated by Django 3.2.5 on 2023-11-08 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0003_rename_user_user_username_alter_comment_author_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='consent_choice',
            new_name='can_be_contacted',
        ),
    ]
