# Generated by Django 3.2.5 on 2023-11-08 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0004_rename_consent_choice_user_can_be_contacted'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_data_be_shared',
            field=models.BooleanField(default=False),
        ),
    ]
